In [22]:
import pandas as pd

In [23]:
df = pd.read_csv('Mall_Customers.csv')

In [24]:
df.head()

   CustomerID   Genre  Age  Annual Income (k$)  Spending Score (1-100)
0           1    Male   19                  15                      39
1           2    Male   21                  15                      81
2           3  Female   20                  16                       6
3           4  Female   23                  16                      77
4           5  Female   31                  17                      40

In [25]:
df.shape

(200, 5)

In [26]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 5 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   CustomerID              200 non-null    int64
 1   Genre                   200 non-null    str
 2   Age                     200 non-null    int64
 3   Annual Income (k$)      200 non-null    int64
 4   Spending Score (1-100)  200 non-null    int64
dtypes: int64(4), str(1)
memory usage: 8.9 KB

In [27]:
df.isnull().sum()

CustomerID                0
Genre                     0
Age                       0
Annual Income (k$)        0
Spending Score (1-100)    0
dtype: int64

In [28]:
df['Genre'].unique()

<ArrowStringArray>
['Male', 'Female']
Length: 2, dtype: str

In [29]:
df.rename(columns={
    'CustomerID': 'customer_id',
    'Genre': 'gender',
    'Age': 'age',
    'Annual Income (k$)': 'annual_income_k',
    'Spending Score (1-100)': 'spending_score'
}, inplace=True)

In [30]:
df.drop_duplicates(inplace=True)

In [31]:
df.dropna(inplace=True)

In [32]:
df['gender'] = df['gender'].astype(str).str.strip().str.capitalize()

In [33]:
df['customer_id'] = df['customer_id'].astype(int)
df['gender'] = df['gender'].astype('category')
df['age'] = df['age'].astype(int)
df['annual_income_k'] = df['annual_income_k'].astype(int)
df['spending_score'] = df['spending_score'].astype(int)

In [34]:
df.dtypes

customer_id           int64
gender             category
age                   int64
annual_income_k       int64
spending_score        int64
dtype: object

In [35]:
df.isnull().sum()

customer_id        0
gender             0
age                0
annual_income_k    0
spending_score     0
dtype: int64

In [36]:
df.duplicated().sum()

np.int64(0)

In [37]:
df.columns

Index(['customer_id', 'gender', 'age', 'annual_income_k', 'spending_score'], dtype='str')

In [38]:
df.head()

   customer_id  gender  age  annual_income_k  spending_score
0            1    Male   19               15              39
1            2    Male   21               15              81
2            3  Female   20               16               6
3            4  Female   23               16              77
4            5  Female   31               17              40

In [39]:
df.shape

(200, 5)

In [40]:
df['age'].min(), df['age'].max()

(np.int64(18), np.int64(70))

In [41]:
df['spending_score'].min(), df['spending_score'].max()

(np.int64(1), np.int64(99))

In [42]:
df.to_csv('cleaned_mall_customers.csv', index=False)

print("Data cleaning complete!")
print("Cleaned dataset saved as cleaned_mall_customers.csv")

Data cleaning complete!
Cleaned dataset saved as cleaned_mall_customers.csv

In [43]:
df['annual_income_k'].min(), df['annual_income_k'].max()

(np.int64(15), np.int64(137))

In [44]:
df.describe()

       customer_id         age  annual_income_k  spending_score
count   200.000000  200.000000       200.000000      200.000000
mean    100.500000   38.850000        60.560000       50.200000
std      57.879185   13.969007        26.264721       25.823522
min       1.000000   18.000000        15.000000        1.000000
25%      50.750000   28.750000        41.500000       34.750000
50%     100.500000   36.000000        61.500000       50.000000
75%     150.250000   49.000000        78.000000       73.000000
max     200.000000   70.000000       137.000000       99.000000