In [1]:
import pandas as pd

In [2]:
import numpy as np

In [3]:
df=pd.read_csv(r'/Users/udaykumarreddy/Desktop/Advanced Data Science Technique/Linear Regression/house_prices_practice.csv')

In [4]:
df.head

<bound method NDFrame.head of       Id  OverallQual  GrLivArea  GarageCars  TotalBsmtSF  YearBuilt  \
0      1            7       1560           0         1658       1969
1      2            4       2827           2         1319       2012
2      3            8       3920           0          841       2010
3      4            5       3044           0         1058       1998
4      5            7        801           1         2428       2020
..   ...          ...        ...         ...          ...        ...
295  296            1       3495           1         1792       1954
296  297            5       3438           3         1266       2003
297  298            6       1992           0         1148       1996
298  299            3       3722           1         1407       1998
299  300            9       1667           0          988       1958

     FullBath  BedroomAbvGr  LotArea  SalePrice
0           2             1     8059     177106
1           3             4    13530     301044
2           1             4     9010     360609
3           0             4    13207     240556
4           0             1     9117     193656
..        ...           ...      ...        ...
295         2             5     4978     250604
296         0             1     9373     329906
297         1             1     7907     184623
298         1             1     8097     303345
299         2             1    14553     204982

[300 rows x 10 columns]>

In [5]:
print(df.head())

   Id  OverallQual  GrLivArea  GarageCars  TotalBsmtSF  YearBuilt  FullBath  \
0   1            7       1560           0         1658       1969         2
1   2            4       2827           2         1319       2012         3
2   3            8       3920           0          841       2010         1
3   4            5       3044           0         1058       1998         0
4   5            7        801           1         2428       2020         0

   BedroomAbvGr  LotArea  SalePrice
0             1     8059     177106
1             4    13530     301044
2             4     9010     360609
3             4    13207     240556
4             1     9117     193656

In [6]:
print(df.shape)

(300, 10)

In [7]:
print(df.dtypes)

Id              int64
OverallQual     int64
GrLivArea       int64
GarageCars      int64
TotalBsmtSF     int64
YearBuilt       int64
FullBath        int64
BedroomAbvGr    int64
LotArea         int64
SalePrice       int64
dtype: object

In [8]:
print(df.isnull().sum())

Id              0
OverallQual     0
GrLivArea       0
GarageCars      0
TotalBsmtSF     0
YearBuilt       0
FullBath        0
BedroomAbvGr    0
LotArea         0
SalePrice       0
dtype: int64

In [9]:
print(df.duplicated().sum())

0

In [10]:
df.describe()

,Id,OverallQual,GrLivArea,GarageCars,TotalBsmtSF,YearBuilt,FullBath,BedroomAbvGr,LotArea,SalePrice
count,300.000000,300.000000,300.000000,300.000000,300.000000,300.000000,300.000000,300.000000,300.000000,300.000000
mean,150.500000,5.326667,2307.386667,1.330000,1468.796667,1986.163333,1.523333,2.926667,8969.453333,252262.903333
std,86.746758,2.873001,1042.561303,1.109898,672.333705,21.377089,1.131543,1.456604,3753.531132,74998.055214
min,1.000000,1.000000,504.000000,0.000000,303.000000,1950.000000,0.000000,1.000000,2009.000000,82494.000000
25%,75.750000,3.000000,1392.250000,0.000000,903.000000,1967.000000,0.000000,2.000000,5996.250000,190355.250000
50%,150.500000,5.000000,2265.500000,1.000000,1502.000000,1986.000000,2.000000,3.000000,9031.000000,251292.500000
75%,225.250000,8.000000,3306.500000,2.000000,2129.500000,2004.250000,3.000000,4.000000,12316.000000,307105.000000
max,300.000000,10.000000,3998.000000,3.000000,2492.000000,2023.000000,3.000000,5.000000,14987.000000,435291.000000

In [11]:
print(df.select_dtypes('number').columns)

Index(['Id', 'OverallQual', 'GrLivArea', 'GarageCars', 'TotalBsmtSF',
       'YearBuilt', 'FullBath', 'BedroomAbvGr', 'LotArea', 'SalePrice'],
      dtype='str')

In [12]:
print(df.select_dtypes('object').columns)

Index([], dtype='str')

In [13]:
x = df[['OverallQual',
        'GrLivArea',
        'GarageCars',
        'TotalBsmtSF',
        'YearBuilt',
        'FullBath',
        'BedroomAbvGr',
        'LotArea']]

In [14]:
y = df['SalePrice']

In [15]:
from sklearn.model_selection import train_test_split

In [16]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=12)

In [17]:
print(x_train.shape)

(240, 8)

In [18]:
print(x_test.shape)

(60, 8)

In [25]:
y = df['SalePrice']

In [26]:
from sklearn.linear_model import LinearRegression

In [27]:
model = LinearRegression()

In [28]:
model.fit(x_train, y_train)

LinearRegression()

In [29]:
y_pred = model.predict(x_test)

In [30]:
print(y_pred)

[322282.54318339 385458.15265493 207237.33477461 330855.22338302
 121908.96253398 375108.10558674 314546.53143914 208021.40165097
 195653.48014182 263678.98794911 301812.54037438 193196.30280169
 288125.8293911  287327.13221277 279901.60413633 259500.11596118
 244544.14681399  92726.42536953 195930.78396675 380829.69796294
 186627.69311551 226935.83169137 236240.71994047 163129.99885131
 253733.72020922 251503.62688526 209578.9074317  330829.30525549
 174989.22697722 165515.57350818 169754.92556337 219836.21560033
 242926.15981885 219144.61969513 395918.92166136 252044.24341115
 280225.9308696  378973.90634702 148145.86406382 317629.90704935
 302248.44565522 143897.85285476 169141.58142888 315231.93304144
 216759.68204755 297999.35376512 257229.93545587 244289.26222301
 340693.30193849 368655.09251521 194289.10836118 269220.63257097
 192068.90251095 210628.44545573 292775.83192997 115431.99476816
 206191.59940719 282692.11991387 118876.94713104 169476.9318799 ]

In [31]:
from sklearn.metrics import r2_score

In [32]:
r2 = r2_score(y_test, y_pred)

In [34]:
print(r2)

0.9776064358983921

In [39]:
comparison = pd.DataFrame({
    'Actual': y_test.values,
    'Predicted': y_pred})
comparison

    Actual      Predicted
0   326572  322282.543183
1   384804  385458.152655
2   199783  207237.334775
3   309211  330855.223383
4   123716  121908.962534
5   353246  375108.105587
6   301044  314546.531439
7   225589  208021.401651
8   178408  195653.480142
9   262938  263678.987949
10  317598  301812.540374
11  181535  193196.302802
12  296330  288125.829391
13  306422  287327.132213
14  270247  279901.604136
15  250604  259500.115961
16  241072  244544.146814
17   82494   92726.425370
18  183022  195930.783967
19  385176  380829.697963
20  174649  186627.693116
21  217440  226935.831691
22  221041  236240.719940
23  155462  163129.998851
24  260686  253733.720209
25  252495  251503.626885
26  227398  209578.907432
27  343023  330829.305255
28  162744  174989.226977
29  165288  165515.573508
30  176871  169754.925563
31  209288  219836.215600
32  259421  242926.159819
33  226280  219144.619695
34  405664  395918.921661
35  240556  252044.243411
36  285964  280225.930870
37  361922  378973.906347
38  156623  148145.864064
39  328244  317629.907049
40  305681  302248.445655
41  145539  143897.852855
42  186675  169141.581429
43  319207  315231.933041
44  210516  216759.682048
45  303727  297999.353765
46  263814  257229.935456
47  249294  244289.262223
48  350830  340693.301938
49  382768  368655.092515
50  186202  194289.108361
51  285161  269220.632571
52  207531  192068.902511
53  220641  210628.445456
54  302296  292775.831930
55  115204  115431.994768
56  190530  206191.599407
57  289968  282692.119914
58  134900  118876.947131
59  161577  169476.931880